version: '3.7'
services:
  teste:
    image: gblbjj/deploy 
    ports:
      - 8083:8083
    networks:
      - simple-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
     
 
networks:
  simple-net:
    driver: overlay
    external: true   




   